In [1]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


/kaggle/input/house-prices-advanced-regression-techniques/sample_submission.csv
/kaggle/input/house-prices-advanced-regression-techniques/data_description.txt
/kaggle/input/house-prices-advanced-regression-techniques/train.csv
/kaggle/input/house-prices-advanced-regression-techniques/test.csv


In [2]:
train_df = pd.read_csv('/kaggle/input/house-prices-advanced-regression-techniques/train.csv')
train_df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal     208500  
1         5   2007        WD         Normal     181500  
2         9   2008        WD         Normal     223500  
3         2   2006        WD        Abnorml     140000  
4        12   2008        WD         Normal     250000  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

In [3]:
test_df = pd.read_csv('/kaggle/input/house-prices-advanced-regression-techniques/test.csv')
test_df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0     1461          20       RH         80.0    11622   Pave   NaN      Reg   
1     1462          20       RL         81.0    14267   Pave   NaN      IR1   
2     1463          60       RL         74.0    13830   Pave   NaN      IR1   
3     1464          60       RL         78.0     9978   Pave   NaN      IR1   
4     1465         120       RL         43.0     5005   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1454  2915         160       RM         21.0     1936   Pave   NaN      Reg   
1455  2916         160       RM         21.0     1894   Pave   NaN      Reg   
1456  2917          20       RL        160.0    20000   Pave   NaN      Reg   
1457  2918          85       RL         62.0    10441   Pave   NaN      Reg   
1458  2919          60       RL         74.0     9627   Pave   NaN      Reg   

     LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence  \
0            Lvl    AllPub  ...         120        0    NaN  MnPrv   
1            Lvl    AllPub  ...           0        0    NaN    NaN   
2            Lvl    AllPub  ...           0        0    NaN  MnPrv   
3            Lvl    AllPub  ...           0        0    NaN    NaN   
4            HLS    AllPub  ...         144        0    NaN    NaN   
...          ...       ...  ...         ...      ...    ...    ...   
1454         Lvl    AllPub  ...           0        0    NaN    NaN   
1455         Lvl    AllPub  ...           0        0    NaN    NaN   
1456         Lvl    AllPub  ...           0        0    NaN    NaN   
1457         Lvl    AllPub  ...           0        0    NaN  MnPrv   
1458         Lvl    AllPub  ...           0        0    NaN    NaN   

     MiscFeature MiscVal MoSold  YrSold  SaleType  SaleCondition  
0            NaN       0      6    2010        WD         Normal  
1           Gar2   12500      6    2010        WD         Normal  
2            NaN       0      3    2010        WD         Normal  
3            NaN       0      6    2010        WD         Normal  
4            NaN       0      1    2010        WD         Normal  
...          ...     ...    ...     ...       ...            ...  
1454         NaN       0      6    2006        WD         Normal  
1455         NaN       0      4    2006        WD        Abnorml  
1456         NaN       0      9    2006        WD        Abnorml  
1457        Shed     700      7    2006        WD         Normal  
1458         NaN       0     11    2006        WD         Normal  

[1459 rows x 80 columns]

In [4]:
# first test with the mean of sale price
test_df['SalePrice'] = pd.Series([train_df['SalePrice'].mean()]*len(train_df))
test_df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0     1461          20       RH         80.0    11622   Pave   NaN      Reg   
1     1462          20       RL         81.0    14267   Pave   NaN      IR1   
2     1463          60       RL         74.0    13830   Pave   NaN      IR1   
3     1464          60       RL         78.0     9978   Pave   NaN      IR1   
4     1465         120       RL         43.0     5005   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1454  2915         160       RM         21.0     1936   Pave   NaN      Reg   
1455  2916         160       RM         21.0     1894   Pave   NaN      Reg   
1456  2917          20       RL        160.0    20000   Pave   NaN      Reg   
1457  2918          85       RL         62.0    10441   Pave   NaN      Reg   
1458  2919          60       RL         74.0     9627   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN        Gar2   12500   
2            Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            HLS    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1454         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  MnPrv        Shed     700   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition     SalePrice  
0         6   2010        WD         Normal  180921.19589  
1         6   2010        WD         Normal  180921.19589  
2         3   2010        WD         Normal  180921.19589  
3         6   2010        WD         Normal  180921.19589  
4         1   2010        WD         Normal  180921.19589  
...     ...    ...       ...            ...           ...  
1454      6   2006        WD         Normal  180921.19589  
1455      4   2006        WD        Abnorml  180921.19589  
1456      9   2006        WD        Abnorml  180921.19589  
1457      7   2006        WD         Normal  180921.19589  
1458     11   2006        WD         Normal  180921.19589  

[1459 rows x 81 columns]

In [5]:
# the output will be
test_df[['Id','SalePrice']].to_csv('average_prediction.csv',index=False)

# of course this is not a good output: the mean can't be a good prediction
# but it's something!!

In [6]:
# we use 2 columns for our model

from copy import deepcopy

train_df_sub = deepcopy(train_df[['MSSubClass', 'LotFrontage' ,'SalePrice']])

train_df_sub

MSSubClass  LotFrontage  SalePrice
0             60         65.0     208500
1             20         80.0     181500
2             60         68.0     223500
3             70         60.0     140000
4             60         84.0     250000
...          ...          ...        ...
1455          60         62.0     175000
1456          20         85.0     210000
1457          70         66.0     266500
1458          20         68.0     142125
1459          20         75.0     147500

[1460 rows x 3 columns]

In [11]:
train_df_sub = train_df_sub.fillna(train_df_sub.mean())

In [12]:
X_train = train_df_sub.to_numpy()[:,:-1]
Y_trainany = train_df_sub.to_numpy()[:,-1]

Y_train

array([208500., 181500., 223500., ..., 266500., 142125., 147500.])

In [14]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression().fit(X_train, Y_train)

lr.coef_

array([  75.96942776, 1260.11397803])

In [15]:
lr.intercept_

88327.8118861935

In [17]:
60*75.96942776 + 65*1260.11397803+88327.8118861935


174793.3861237435

In [18]:
train_df_sub['linear_prediction']= lr.predict(X_train)
train_df_sub

MSSubClass  LotFrontage  SalePrice  linear_prediction
0             60         65.0     208500      174793.386124
1             20         80.0     181500      190656.318684
2             60         68.0     223500      178573.728058
3             70         60.0     140000      169252.510511
4             60         84.0     250000      198735.551706
...          ...          ...        ...                ...
1455          60         62.0     175000      171013.044190
1456          20         85.0     210000      196956.888574
1457          70         66.0     266500      176813.194379
1458          20         68.0     142125      175534.950948
1459          20         75.0     147500      184355.748794

[1460 rows x 4 columns]

In [19]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(train_df_sub['SalePrice'],train_df_sub['linear_prediction'])

54381.25047406032

In [20]:
test_df_sub= deepcopy(test_df[['MSSubClass', 'LotFrontage']])

test_df_sub

MSSubClass  LotFrontage
0             20         80.0
1             20         81.0
2             60         74.0
3             60         78.0
4            120         43.0
...          ...          ...
1454         160         21.0
1455         160         21.0
1456          20        160.0
1457          85         62.0
1458          60         74.0

[1459 rows x 2 columns]

In [23]:
test_df_sub = test_df_sub.fillna(test_df_sub.mean())

In [26]:
X_test = test_df_sub.to_numpy()
X_test

array([[ 20.,  80.],
       [ 20.,  81.],
       [ 60.,  74.],
       ...,
       [ 20., 160.],
       [ 85.,  62.],
       [ 60.,  74.]])

In [31]:
test_df['SalePrice']= lr.predict(X_test)
test_df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0     1461          20       RH         80.0    11622   Pave   NaN      Reg   
1     1462          20       RL         81.0    14267   Pave   NaN      IR1   
2     1463          60       RL         74.0    13830   Pave   NaN      IR1   
3     1464          60       RL         78.0     9978   Pave   NaN      IR1   
4     1465         120       RL         43.0     5005   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1454  2915         160       RM         21.0     1936   Pave   NaN      Reg   
1455  2916         160       RM         21.0     1894   Pave   NaN      Reg   
1456  2917          20       RL        160.0    20000   Pave   NaN      Reg   
1457  2918          85       RL         62.0    10441   Pave   NaN      Reg   
1458  2919          60       RL         74.0     9627   Pave   NaN      Reg   

     LandContour Utilities  ... PoolQC  Fence MiscFeature MiscVal MoSold  \
0            Lvl    AllPub  ...    NaN  MnPrv         NaN       0      6   
1            Lvl    AllPub  ...    NaN    NaN        Gar2   12500      6   
2            Lvl    AllPub  ...    NaN  MnPrv         NaN       0      3   
3            Lvl    AllPub  ...    NaN    NaN         NaN       0      6   
4            HLS    AllPub  ...    NaN    NaN         NaN       0      1   
...          ...       ...  ...    ...    ...         ...     ...    ...   
1454         Lvl    AllPub  ...    NaN    NaN         NaN       0      6   
1455         Lvl    AllPub  ...    NaN    NaN         NaN       0      4   
1456         Lvl    AllPub  ...    NaN    NaN         NaN       0      9   
1457         Lvl    AllPub  ...    NaN  MnPrv        Shed     700      7   
1458         Lvl    AllPub  ...    NaN    NaN         NaN       0     11   

     YrSold SaleType  SaleCondition      SalePrice  linear_prediction  
0      2010       WD         Normal  190656.318684      190656.318684  
1      2010       WD         Normal  191916.432662      191916.432662  
2      2010       WD         Normal  186134.411926      186134.411926  
3      2010       WD         Normal  191174.867838      191174.867838  
4      2010       WD         Normal  151629.044272      151629.044272  
...     ...      ...            ...            ...                ...  
1454   2006       WD         Normal  126945.313866      126945.313866  
1455   2006       WD        Abnorml  126945.313866      126945.313866  
1456   2006       WD        Abnorml  291465.436927      291465.436927  
1457   2006       WD         Normal  172912.279884      172912.279884  
1458   2006       WD         Normal  186134.411926      186134.411926  

[1459 rows x 82 columns]

In [32]:
test_df[['Id','SalePrice']].to_csv('linear_prediction.csv',index=False)